stages:
  - build

variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_DRIVER: overlay2

# Build the image
build-image:
  stage: build
  image: 'debian:buster'
  script:
    # Dependencies
    - apt-get update
    - apt-get -y install git vim parted quilt coreutils qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin rsync grep udev xz-utils curl xxd file kmod kpartx bc

    # Set up build
    - dpkg-reconfigure qemu-user-static
    - ./prepare.sh
    - touch pi-gen/stage{2,{4,5}-pokoe}/SKIP_IMAGES

    # Test build
    - (cd pi-gen/ && ./build.sh)
