#!/bin/sh

# Use dark mode, set DPI scaling
export GTK_THEME=Adwaita:dark
export GDK_DPI_SCALE=1.5

# Start PulseAudio
# TODO: create systemd service for audio
pulseaudio --high-priority --realtime --no-cpu-limit -D

# Start PokoeBox Player
xinit /opt/pokoebox/pokoebox-player
