#!/bin/sh

# Use dark mode, set DPI scaling
export GTK_THEME=Adwaita:dark
export GDK_DPI_SCALE=1.5

# Start PulseAudio
# TODO: create systemd service for this
pulseaudio --high-priority --realtime --no-cpu-limit -D

# Start screensaver daemon
# TODO: create systemd service for this
runuser -l pokoe -c 'sleep 10; export DISPLAY=:0; xscreensaver -no-splash' &

# Start MPRIS proxy for bluetooth
# TODO: create systemd service for this
runuser -l pokoe -c 'mpris-proxy' &

# Start PokoeBox Player
xinit /opt/pokoebox/pokoebox-player
